### ISSUE TITLE
请问下数据什么时候会放出来呢？

### ISSUE THREAD

**Issue by shuxiaobo** [gmftbyGMFTBY/OpenDialog#1]
请问下数据什么时候会放出来呢？因为看到很多数据集貌似不是中文的，而且也没有链接，想搞点数据，谢谢~

**Comment by gmftbyGMFTBY** [comment]
谢谢你的关注，之后会公布一些处理好的公开发布的数据，还有我自己爬的一些数据。

**Comment by shuxiaobo** [comment]
感谢！

**Comment by gmftbyGMFTBY** [comment]
对了，在`data`目录下可以看到很多的数据集的子目录，里面的`README.md`文件记录了数据的来源和出处（论文或者链接），希望对你有帮助。

**Comment by shuxiaobo** [comment]
看到啦，已经在下载和处理了~感谢

**Comment by shuxiaobo** [comment]
@gmftbyGMFTBY 关于数据话题的问题，感谢您放出来的数据，数据的内容很多，代码中有关于聊天话题的设计，但是数据中却没有话题的标签，请问这个话题是有单独的训练数据吗？

**Comment by gmftbyGMFTBY** [comment]
谢谢你的关注，我想你是看到了代码中出现的topic参数了。是这样的，训练模型的时候并没有使用topic来建模。使用topic的初衷是为了兼容SMP-MCC 2020的群聊对话比赛，topic信息并没有参与训练过程，最多在生成式响应结果重排中用fasttext训练了一个topic分类器

**Comment by shuxiaobo** [comment]
用fasttext训练的分类器，数据是比赛的数据通过处理出来的吗？我正好看到了这里，所以有些疑惑数据问题

**Comment by gmftbyGMFTBY** [comment]
是的，比赛官方给的数据，可以在`data/doubangroup`下面找到，是不同的topic对应的文件，我训练了一个fasttext分类器，因为这个项目我的`README.md`和使用手则还没写完，所以你可能还没有找到训练fasttext的命令。在 `multiview/topic.py` 中可以找到，到时候`README.md`我会补充完全的

**Comment by shuxiaobo** [comment]
我刚看了下`doubangroup`的文件，里面只有一个`train.txt`，其他文件夹也没有按照topic分的数据

**Comment by gmftbyGMFTBY** [comment]
train.txt是我处理后用来训练shen过程模型的，分类topic的数据可以参见原仓库 https://github.com/iseesaw/SMP-MCC2020
